### ISSUE TITLE
❓ Questions / Help / Support Cuda out of memory

### ISSUE THREAD

**Issue by fionafytan0809-coder** [snakers4/silero-vad#683]
Hello, 
I am fine-tuning the model using the default config.yaml in nvidia V100. The training phase proceeds normally, but I encounter a CUDA out of memory error during the validation phase. May I ask what could be the reason for this?

**Comment by snakers4** [comment]
The most obvious idea - too long audios.
The optimal training size is 15-20 seconds max.

**Comment by fionafytan0809-coder** [comment]
> The most obvious idea - too long audios. The optimal training size is 15-20 seconds max.

Yeah，Thanks.  I have resolved this issue. It was indeed caused by too long audios, as your code did not set a maximum audio truncation function for the validation phase.  Other question,  Do you provide code for single-machine multi-GPU parallel training? If I have 1000 hours of data, would you recommend using multiple GPU cards for parallel training?

**Comment by snakers4** [comment]
You will have to add DDP by yourself.
The code provided is just a minimalist boilerplate to build upon.
